### ISSUE TITLE
Chore:update NPM packages (esp formidable)

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-model-graphql-api#17]
done when:
 - [ ] https://github.com/GNS-Science/nshm-model-graphql-api/security/dependabot/22 is resolved
 - [ ] new deployments to deploy-test and prod

**Comment by chrisbc** [comment]
## About the Formidable Vulnerablity:

the **formidable** NPM library is a serverless framework dependency. We use this for deployment related tasks only, it's not a AWS runtime component, and none of our API services, provide a form upload feature (where this vulnerability applies). 

### Resolution:

We should address this [as explained here](https://github.com/serverless/serverless/issues/12442) as part of normal maintenance cycle, so future deployments include this fix.

**Comment by rbambirra** [comment]
Can someone provide an estimated timeline for the completion of this task?

**Comment by chrisbc** [comment]
in #20
